project:
  type: website

website:
  title: "Editor-Selected JASA Reproducibility Award"
  navbar:
    right:
      - about.qmd
      - href: index.qmd
        text: About the award 
      
format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

